<?php

return [
    'GEOSERVER_WORKSPACE' => env('GEOSERVER_WORKSPACE'),
    'GEOSERVER' => env('GEOSERVER'),
    'GEOSERVER_URL' => env('GEOSERVER_URL'),
    'PGSQL_BIN_PATH' => env('PGSQL_BIN_PATH'),
    'AUTH_KEY' => env('AUTH_KEY'),
    'GEOSERVER_USERNAME' => env('GEOSERVER_USERNAME'),
    'GEOSERVER_AUTH_PROXY' => env('GEOSERVER_AUTH_PROXY'),
    'GEOSERVER_BBOX' => env(
    'GEOSERVER_BBOX',
    '9499294.829600912,3201237.9884866863,9505273.468106326,3207651.002046891'
),
    'GEOSERVER_WIDTH'  => env('GEOSERVER_WIDTH', 768),
    'GEOSERVER_HEIGHT' => env('GEOSERVER_HEIGHT', 704),
    # BASE MAP API KEYS
    'API_KEY_BING' => env('API_KEY_BING'),
    'API_KEY_GOOGLE' => env('API_KEY_GOOGLE'),
];
?>